import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { inter } from '@/app/ui/fonts';
import NavLinks from "./ui/navLinks";
import styles from "./page.module.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}>
        <div className={styles.root}>
          <header className={styles.header}>Header</header>
          <div className={styles.layout}>
            <nav className={styles.nav}><NavLinks /></nav>
            <main className={styles.main}>{children}</main>
            <aside className={styles.aside}>Sidebar</aside>
          </div>
          <footer className={styles.footer}>Footer</footer>
        </div>
      </body>
    </html>
  );
}
